# Site settings
title: DLM Negative Research
email: dont.lose.money.dlm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Negative Research focuses on what could go wrong in the financial markets first!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.dlmnegativeresearch.com" # the base hostname & protocol for your site
twitter_username: DLM_NegResearch

# Build settings
markdown: kramdown
